# Cargo.toml
[package]
name = "kensaku"
version = "1.0.0"
edition = "2021"

[dependencies]
console = "0.15.11"
dirs = "6"
rand = "0.9.1"
serde = { version = "1.0", features = ["derive"] }
sysinfo = "0.35.1"
toml = "0.8"
users = "0.11"

